title: "Ayman Shams"
author: "Ayman Shams"
description: "AI Research | RL • Vision • Graphics • Generative AI"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

show_excerpts: true
show_frame: false
show_sidebar: true
show_minimal: false

navigation:
  - {file: "index.md", title: "RL & Robotics", icon: robot}
  - {file: "archive.md", title: "Graphics & VFX", icon: cube}
  - {file: "README.md", title: "Vision & GenAI", icon: eye}
  - {file: "writing.md", title: "Blogs", icon: pen-nib}

external:
  - {title: Email, icon: envelope, url: "mailto:ayman.shams07@gmail.com"}
  - {title: GitHub, icon: github, url: "https://github.com/aymanshams07"}
  - {title: Medium, icon: medium, url: "https://medium.com/@ayman.shams07"}

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: niklasbuschmann/contrast@v2.11
